### ISSUE TITLE
Reset analytics

### ISSUE THREAD

**Issue by robertosannazzaro** [jrieke/streamlit-analytics#2]
Hello! First of all thanks for this. It is really great to have something like built for Streamlit!

I have tried saving the analytics as JSON, and I have noticed that if I delete the `.json` file, once I run the app again I will still get my "old" analytics files. Is there a wy to reset the tracking and start from zero at some point?

**Comment by jrieke** [comment]
Hey @robertosannazzaro, at the moment the easiest solution would be to restart your streamlit app (i.e. re-run `streamlit run`), then all metrics should be reset. I don't have time for this project right now but I hope I can get back to it during the next weeks, then I'll think about how a programmatic reset could be implemented! :)

**Comment by jrieke** [comment]
@robertosannazzaro The newest version (v0.2.1) has a section at the bottom of the page that allows you to reset all results (see image). Let me know if that works for you and feel free to re-open if not!

![image](https://user-images.githubusercontent.com/5103165/106334600-4efb4b80-628b-11eb-8c69-ed36bb7cd814.png)

**Comment by robertosannazzaro** [comment]
Hi @jrieke, tested and like it very much! Thanks for pushing this one!

**Comment by joshua-bowden** [comment]
would be great to be able to disable this in code, especially since these analytics are mostly used with no password/ not secure
