### ISSUE TITLE
streamlit >= 1.12.0 not supporting this package

### ISSUE THREAD

**Issue by zivshapiraintel** [jrieke/streamlit-analytics#21]
streamlit >= 1.12.0 not supporting this package

When upgrading our working code from streamlit 1.11.1 to 1.12.0, this package breaks

**Comment by jrieke** [comment]
Hey, I changed the implementation to work with `st.session_state` now, so it should be a lot more stable. Check out release 0.4.1, it's tested with Streamlit 1.13.0.
