### ISSUE TITLE
Add support for sliders / tuples in widget interactions

### ISSUE THREAD

**Issue by eschares** [jrieke/streamlit-analytics#6]
Almost all my widets are setup as double-sided sliders, which return a tuple of values.  This produces an error in the widget interactions section of the report as tuples are not supported.

![slider](https://i.ibb.co/QPtzXtx/slider.jpg)

I don't know what it would take to enable this, but I would like to have that functionality available to me.

**Comment by rustyBilges** [comment]
I have run into the same problem and agree that this functionality would be great to have. I will have a think about how it could be done.

**Comment by jrieke** [comment]
Hey, thx for reporting and sorry for the long delay!

Just added a fix for this, tuple values now get converted to strings (`(0, 100)` -> `"0 - 100"`). Hope this works and doesn't cause other problems. It's on PyPI as version 0.3.1 :)
