### ISSUE TITLE
does this need to be updated to reflect that session state is no longer beta?

### ISSUE THREAD

**Issue by fredzannarbor** [jrieke/streamlit-analytics#8]
# Only set this to True if you're using Streamlit's session state beta!!!
session_state_beta = False
if session_state_beta:
    from streamlit import beta_session_state as get_session_state
else:
    from .session_state import get as get_session_state

**Comment by jrieke** [comment]
Hey, thx for flagging this! The released version of session state uses a different API than the beta version, so simply using the released version doesn't work. It would require changing potentially a lot of stuff throughout the codebase (which I don't have time for).
