### ISSUE TITLE
Load Json to persist data between deployments

### ISSUE THREAD

**Issue by Uranium2** [jrieke/streamlit-analytics#9]
Hello,

I see you used firebase to do persist data between deployments, would it be possible to add this feature with json?

Context:

In my case the streamlit app is deployed on a docker and we have no persistence of volume (security constraint), so I was thinking about uploading the json on a server at fixed frequency rate. For example a task that will upload the json file each 30 seconds.
    
Then if the docker dies, we could fetch this json and load it in your tracker to persist the data.

**Comment by Uranium2** [comment]
Made a Pull Request for this feature : https://github.com/jrieke/streamlit-analytics/pull/10

**Comment by jrieke** [comment]
Merged with #10
